name: Build & Sign

on:
  release:
    types: [published]
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
          
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            assemble
            assembleplayStoreRelease
            
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/playStore/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          BUILD_TOOLS_VERSION: "30.0.2"
            
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ${{steps.sign_app.outputs.signedReleaseFile}}
          destination: s3://metapebble/meta-pebble/meta-pebble-${{ github.ref_name }}.apk
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-east-1
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.sign_app.outputs.signedReleaseFile}}
          asset_name: meta-pebble-${{ github.ref_name }}.apk
          tag: ${{ github.ref }}
